env:
    browser: true
    es2021: true
    node: true
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:cypress/recommended'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
plugins:
    - react
    - cypress
rules:
    {
        no-unused-vars: warn,
        sort-imports:
            [
                warn,
                {
                    memberSyntaxSortOrder: [single, multiple, all, none],
                    allowSeparatedGroups: false,
                    ignoreCase: true,
                },
            ],
        react/prop-types: warn,
        react/jsx-uses-react: warn,
        react/jsx-uses-vars: warn,
        react/no-unescaped-entities: warn,
        react/react-in-jsx-scope: off,
        react/jsx-key: warn,
        no-duplicate-imports: warn,
        no-mixed-spaces-and-tabs: warn,
    }
