version: 2.1
jobs:
    test:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: yarn
            - run: yarn test
            - store_test_results:
                  path: test-results
            - store_artifacts:
                  path: cypress/videos
            - store_artifacts:
                  path: cypress/screenshots
workflows:
    basic:
        jobs:
            - test
