version: 2.1
jobs:
    install:
        docker:
        # replace with your preferred image
        - image: cimg/base:stable
        steps:
        - node/install:
            install-yarn: true 
    build:
        docker:
            - image: cimg/node:17.3.0
        steps:
            - checkout
            - run:
                  name: Build
                  command: yarn build
orbs:
    cypress: cypress-io/cypress@1.29.0
workflows:
    basic:
        jobs:
            - install
            - cypress/run:
                yarn: true 
