version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0
jobs:
    test:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run: yarn
workflows:
    basic:
        jobs:
            - test
            - cypress/run
