version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          executor: cypress/base-14
          start: yarn dev
          parallel: true
          parallelism: 2
          group: 2 machines
          record: true